
export const members = [
    {
        id: 1,
        name: 'James Kwizera',
        title: 'Senior Aircraft Maintenance Engineer',
        location: 'Entebbe, Uganda',
        license: 'AME_CAT_A',
        specializations: ['Mechanical Systems', 'Turbine Engines'],
        yearsExperience: 15,
        verified: true,
        avatar: '👨‍💼',
        bio: 'James is a Senior Licensed Aircraft Maintenance Engineer with over 15 years of hands-on experience in the aviation industry. Specializing in turbine engines and heavy maintenance, he has led maintenance teams for major regional airlines. He is passionate about aviation safety, mentorship for junior engineers, and implementing efficient maintenance procedures.',
        email: 'james.kwizera@aviation-ug.co',
        phone: '+256 700 123 456',
        availability: 'Open to consulting',
        currentEmployer: 'Uganda Airlines',
        certifications: ['B737 NG/MAX Type Rating', 'CRJ900 Type Rating', 'Safety Management Systems'],
        education: 'BSc. Aeronautical Engineering - Kyambogo University',
        languages: ['English', 'Swahili', 'Luganda']
    },
    {
        id: 2,
        name: 'Sarah Ouma',
        title: 'Avionics Technician',
        location: 'Kampala, Uganda',
        license: 'AME_CAT_B',
        specializations: ['Avionics', 'Flight Control Systems'],
        yearsExperience: 8,
        verified: true,
        avatar: '👩‍💼',
        bio: 'Sarah is an accomplished Avionics Technician with a sharp focus on modern flight control systems and digital avionics suites. She is certified on Boeing 737NG/MAX and CRJ900 series. Sarah is a strong advocate for women in aviation STEM roles and actively volunteers in community outreach programs.',
        email: 'sarah.ouma@aeromaint.ug',
        phone: '+256 701 987 654',
        availability: 'Full-time employed',
        currentEmployer: 'Aeromaint Uganda',
        certifications: ['Avionics Level III', 'Composite Repair Basics'],
        education: 'Diploma in Electrical Engineering - Makerere University',
        languages: ['English', 'Luo']
    },
    {
        id: 3,
        name: 'Moses Kamau',
        title: 'Aircraft Maintenance Manager',
        location: 'Jinja, Uganda',
        license: 'AME_CAT_C',
        specializations: ['Maintenance Management', 'Hydraulics', 'Electrical'],
        yearsExperience: 20,
        verified: true,
        avatar: '👨‍💼',
        bio: 'Moses is a results-driven Aircraft Maintenance Manager with a proven track record of ensuring fleet airworthiness and regulatory compliance. His expertise spans team leadership, resource planning, cost optimization, and liaison with regulatory bodies like UCAA. He has successfully managed fleet expansions for cargo operators.',
        email: 'm.kamau@pearlaviation.com',
        phone: '+256 702 555 888',
        availability: 'Open to networking',
        currentEmployer: 'Pearl Aviation',
        certifications: ['EASA Part-145 Management', 'Human Factors in Maintenance'],
        education: 'MBA - ESAMI',
        languages: ['English', 'Swahili']
    },
    {
        id: 4,
        name: 'Florence Mwangi',
        title: 'Junior AME - Trainee',
        location: 'Kampala, Uganda',
        license: 'STUDENT',
        specializations: ['General Maintenance', 'Safety'],
        yearsExperience: 1,
        verified: false,
        avatar: '👩‍🎓',
        bio: 'Florence is an enthusiastic Junior AME Trainee currently completing her practical modules. She is eager to learn and has shown aptitude for general maintenance tasks and safety protocols. She is looking for mentorship and internship opportunities to further her career.',
        email: 'florence.m@student.kia',
        phone: '+256 703 111 222',
        availability: 'Seeking Internship',
        currentEmployer: 'Kajjansi Flying School (Intern)',
        certifications: ['Basic AME Procedures'],
        education: 'Certificate in Aircraft Maintenance - Soroti Flying School',
        languages: ['English']
    },
    {
        id: 5,
        name: 'Peter Koech',
        title: 'Structural Repair Specialist',
        location: 'Entebbe, Uganda',
        license: 'AME_CAT_A',
        specializations: ['Composite Repair', 'Sheet Metal', 'Structures'],
        yearsExperience: 12,
        verified: true,
        avatar: '👨‍💼',
        bio: 'Peter is a highly skilled Structural Repair Specialist with extensive experience in both sheet metal and composite repairs. He is certified to perform complex structural modifications and repairs on various aircraft types. He is known for his precision and attention to detail.',
        email: 'peter.koech@structurerepair.com',
        phone: '+256 704 333 444',
        availability: 'Contractor',
        currentEmployer: 'Freelance / Contractor',
        certifications: ['Advanced Composites Repair', 'Sheet Metal Fabrication'],
        education: 'Diploma in Mechanical Engineering',
        languages: ['English', 'Swahili']
    },
    {
        id: 6,
        name: 'Jane Mwangi',
        title: 'Engine Overhaul Specialist',
        location: 'Dar es Salaam, Tanzania',
        license: 'AME_CAT_A',
        specializations: ['Turbine Engines', 'Piston Engines'],
        yearsExperience: 18,
        verified: true,
        avatar: '👩‍💼',
        bio: 'Jane is a regional expert in engine overhauls, specializing in both turbine and piston engines. She has worked with major MROs across East Africa. Her deep knowledge of engine systems makes her a sought-after consultant for troubleshooting complex engine issues.',
        email: 'jane.mwangi@engineexperts.tz',
        phone: '+255 700 555 666',
        availability: 'Consulting only',
        currentEmployer: 'East African Engine Services',
        certifications: ['PT6A Series Overhaul', 'Lycoming/Continental Engines'],
        education: 'BSc. Mechanical Engineering',
        languages: ['English', 'Swahili']
    },
];

export type Member = typeof members[0];
